### ISSUE TITLE
http://dl.bintray.com/vogellacompany/junit-4-tools/ broken

### ISSUE THREAD

**Issue by vogella** [vogellacompany/codemodify#7]
The tools cannot be installed from http://dl.bintray.com/vogellacompany/junit-4-tools/

**Comment by vogella** [comment]
Fixed via a Jenkins job

**Comment by aminabromand** [comment]
The tool cannot be installed from  http://dl.bintray.com/vogellacompany/junit-4-tools/ again

**Comment by vogella** [comment]
I update the build and the Readme  so that this can be build locally for installation
